services:
  kubes:
      build: .
      volumes:
        - .:/app
      tty: true
      environment:
        # The environment variable credentials that is needed 
        # in django settings for Postgres to work.
        - AWS_ACCESS_KEY_ID=${AWS_ACCESS_KEY_ID}
        - AWS_SECRET_ACCESS_KEY=${AWS_SECRET_ACCESS_KEY}
        - EMAIL_PASSWORD=${EMAIL_PASSWORD}
